title: "Akito Tomita | Portfolio"
description: "研究業績や開発プロジェクトをまとめたポートフォリオサイトです。"
author: "Akito Tomita"

url: "https://TomitaAkito.github.io"
baseurl: ""

github_username: "TomitaAkito"
researchmap_url: "https://researchmap.jp/akitotomita"
github_url: "https://github.com/TomitaAkito"

image: "/assets/images/ogp.png"
twitter:
  card: "summary_large_image"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /news/:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules

future: true